### ISSUE TITLE
import error:most likely due to a circular import

### ISSUE THREAD

**Issue by sudoexec** [asweigart/pyautogui#525]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\someuser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyautogui\__init__.py", line 538, in <module>
    from . import _pyautogui_win as platformModule
ImportError: cannot import name '_pyautogui_win' from partially initialized module 'pyautogui' (most likely due to a circular import) (C:\Users\someuser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyautogui\__init__.py)
```
Maybe related to:
https://github.com/asweigart/pyautogui/blob/e869e5dd9c36022631888555776749ca2f70382b/pyautogui/__init__.py#L539
https://github.com/asweigart/pyautogui/blob/e869e5dd9c36022631888555776749ca2f70382b/pyautogui/_pyautogui_win.py#L7

**Comment by u23a** [comment]
This issue occurs in 0.9.52.
It works in 0.9.51 and 0.9.50

**Comment by wuzhaoqi1015** [comment]
It works in 0.9.51 and 0.9.50 for me

**Comment by amaury-bhg** [comment]
Yes I had the same issue, also present in 0.9.53, on a fresh python install (3.9.13).
Oddly enough, it seems not to occur on my coworkers installs (not fresh python installs).
